name: SonarCloud

on: [push]

jobs:
 sonar:
    name: analyse with sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1.2.0
        with:
          java-version: 8
#       - uses: actions/cache@v1
#         with:
#           path: ~/.m2/repository
#           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
#           restore-keys: |
#             ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-sonarqube
#             ${{ runner.os }}-maven-
      - name: Maven clean
        run: ./mvnw clean
      - name: Run SonarCloud analyse
        run: >
          ./mvnw --batch-mode
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
